import { IsNotEmpty } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class CreatePostDto {
  @ApiProperty({
    example: 'This is a blog post',
    description: 'The title of the post',
  })
  @IsNotEmpty()
  title: string;

  @ApiProperty({
    example: 'This is the description of a blog post',
    description: 'The description of the post',
  })
  @IsNotEmpty()
  description: string;

  @ApiProperty({
    example: 'This is the body of the blog post',
    description: 'The body of the post',
  })
  @IsNotEmpty()
  body: string;
}

export class SuccessCreatePost {
  @ApiProperty({
    example: '98fb7d44-d84b-4df1-9b3a-36e39013f971',
    description: 'The autogenerated id of the post',
  })
  @IsNotEmpty()
  id: string;

  @ApiProperty({
    example: 'This is a blog post',
    description: 'The title of the post',
  })
  @IsNotEmpty()
  title: string;

  @ApiProperty({
    example: 'This is the description of a blog post',
    description: 'The description of the post',
  })
  @IsNotEmpty()
  description: string;

  @ApiProperty({
    example: 'This is the body of the blog post',
    description: 'The body of the post',
  })
  @IsNotEmpty()
  body: string;
}
